### ISSUE TITLE
Generalize to different versions of React

### ISSUE THREAD

**Issue by mcordova47** [collegevine/purescript-elmish-enzyme#3]

**Comment by fsoikin** [comment]
As far as I understand, this is also up to the consumer: you can't install `enzyme` or `react` as a PureScript library, so it's the consumer who should install them, and therefore it's the consumer who would be responsible for matching the versions.

**Comment by fsoikin** [comment]
Oh, I see! You must mean the call to `configure(adapter)`?

**Comment by mcordova47** [comment]
> Oh, I see! You must mean the call to `configure(adapter)`?

Yeah, exactly — it’s currently hardcoded. Addressed in #8.
